# Generated by Django 6.1.1 on 2026-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=100),
            preserve_default=False,
        ),
    ]
